-- Migration: fix_missing_all_period_stats.sql
-- Description: Adds missing "ALL" period metrics to match the HT/FT splits.

ALTER TABLE public.fixture_stats_premium
    ADD COLUMN IF NOT EXISTS h_offsides INTEGER,
    ADD COLUMN IF NOT EXISTS a_offsides INTEGER,
    ADD COLUMN IF NOT EXISTS h_fouls INTEGER,
    ADD COLUMN IF NOT EXISTS a_fouls INTEGER,
    ADD COLUMN IF NOT EXISTS h_dispossessed INTEGER,
    ADD COLUMN IF NOT EXISTS a_dispossessed INTEGER,
    ADD COLUMN IF NOT EXISTS h_hit_woodwork INTEGER,
    ADD COLUMN IF NOT EXISTS a_hit_woodwork INTEGER,
    ADD COLUMN IF NOT EXISTS h_dribbles_success INTEGER,
    ADD COLUMN IF NOT EXISTS a_dribbles_success INTEGER,
    ADD COLUMN IF NOT EXISTS h_dribbles_total INTEGER,
    ADD COLUMN IF NOT EXISTS a_dribbles_total INTEGER,
    -- Missing Period 1 Metrics
    ADD COLUMN IF NOT EXISTS h_ball_recoveries_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_ball_recoveries_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_duels_won_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_duels_won_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_ground_duels_won_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_ground_duels_won_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_aerial_duels_won_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_aerial_duels_won_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_final_third_entries_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_final_third_entries_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_accurate_long_balls_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_accurate_long_balls_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_total_long_balls_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_total_long_balls_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_yellow_cards_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_yellow_cards_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS h_red_cards_p1 INTEGER,
    ADD COLUMN IF NOT EXISTS a_red_cards_p1 INTEGER,
    -- Missing Period 2 Metrics
    ADD COLUMN IF NOT EXISTS h_ball_recoveries_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_ball_recoveries_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_duels_won_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_duels_won_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_ground_duels_won_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_ground_duels_won_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_aerial_duels_won_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_aerial_duels_won_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_final_third_entries_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_final_third_entries_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_accurate_long_balls_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_accurate_long_balls_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_total_long_balls_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_total_long_balls_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_yellow_cards_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_yellow_cards_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS h_red_cards_p2 INTEGER,
    ADD COLUMN IF NOT EXISTS a_red_cards_p2 INTEGER;
